spring:
  application:
    name: spring security 01
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1"   #h2를 inmemory 기반으로 사용
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  #프로젝트가 시작되고 초기화될 때 DB를 초기화 할 수 있도록 설정
  sql:
    init:
      platform: h2
      # 코드가 실행되고 h2 DB 초기화시 관련도니 테이블들이 만들어진다.
      schema-locations: classpath:sql/schema_new.sql
      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8
server:
  port: 8080
jwt:
  #JWT 토큰이 입력되서 들어오는 header 이름을 뜻한다.
  header: token
  #JWT 토큰의 발행자 정보
  issuer: prgrms
  #JWT 토큰을 만들 떄 토큰의 검증을 할 떄 signature를 만들게 되는데 그때 HSoil 알고리즘 사용 -> 64Byte secret-key필요하여 설정
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  #토큰 만료 시간 설정
  expiry-seconds: 60
