spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  #프로젝트가 시작되고 초기화될 때 DB를 초기화 할 수 있도록 설정
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema_new.sql
      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8


server:
  port: 8080