spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./database/spring_security.db;MODE=MYSQL;DB_CLOSE_DELAY=-1"   #inmemory -> file로 사용하기 위해 change
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  #프로젝트가 시작되고 초기화될 때 DB를 초기화 할 수 있도록 설정
  sql:
    init:
      platform: h2
      #mode: default=embedded    h2를 inmemory 사용하면 상관없는데 file기반으로 사용하려면 설정해주어야 초기화 시 관련 테이블이 만들어진다.
      mode: always
      # 코드가 실행되고 h2 DB 초기화시 관련도니 테이블들이 만들어진다.
      schema-locations: classpath:sql/schema_new.sql,classpath:org/springframework/session/jdbc/schema-h2.sql
      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8


server:
  port: 8080